ORG_PROFILE = """
Organization: YEA Today (Youth Entrepreneurship Alliance Today)
Type: 501(c)(3) National Nonprofit
Mission: To develop entrepreneurship programs for youth across the United States, empowering young people with business skills, mindset, and networks to create economic opportunity for themselves and their communities.

Programs:
- Youth entrepreneurship workshops and bootcamps (multi-day intensive programs)
- Mentorship programs connecting youth with business leaders and professionals
- Business plan competitions with prizes and investor feedback
- Financial literacy curriculum (budgeting, credit, investing basics)
- Student-run microenterprise programs

Target Population:
- Youth ages 12-24
- Underserved and underrepresented communities
- Urban and rural youth
- Communities with limited economic opportunity and high unemployment

Geographic Reach: National (US-based programs, multiple states, chapter/partner network)

Key Outcomes and Impact Metrics:
- Number of youth completing programs
- Business plans created and ventures launched
- Increased financial literacy scores among participants
- Youth employment and self-employment rates post-program
- Number of youth-led businesses still operating 12 months later
- Revenue generated by youth-run enterprises
"""

GRANT_CRITERIA = """
Priority Grant Characteristics:
- Amount: $1,000 - $25,000 (primary); note any larger opportunities separately
- Eligibility: Open to 501(c)(3) nonprofit organizations
- Geographic scope: National preferred; multi-state acceptable
- Status: Currently posted (open) OR forecasted (opening soon)

Focus areas that align with YEA Today:
- Youth entrepreneurship and youth business development
- Youth workforce development and career readiness
- Entrepreneurship and business education
- Financial literacy programs for youth
- Youth economic empowerment
- Youth leadership programs
- Community economic development

Grants to skip:
- Restricted only to schools/LEAs (Local Education Agencies) with no nonprofit eligibility
- Requiring a government entity as fiscal agent
- Deadline fewer than 14 days away
- Mission mismatch (health, housing, arts-only, pure research, etc.)
- Restricted to individuals, not organizations
"""

# Search queries sent to Grants.gov
SEARCH_QUERIES = [
    "youth entrepreneurship",
    "youth workforce development",
    "entrepreneurship education nonprofit",
    "youth economic empowerment",
    "youth business skills",
    "financial literacy youth",
    "youth leadership programs",
    "small business youth development",
]
